var language = {
	debug: 1,
	languages: ['en','de'],
	lang: 'en',
	langSelectors: function(){
		if(language.debug>0) console.log('language.langSelectors()');
		var user = DB.getConfig('user');
		language.lang = (user && user.lang)?user.lang:'en';
		var s = $('.language-selector').empty();
		var keys = Object.keys(language.langs);
		for(var i=0;i<keys.length;i++)
			s.append($('<option value="'+keys[i]+'">'+language.langs[keys[i]]._TITLE+'</option>'));
		$('.language-selector').each(function(){
			try {
				$(this).val(language.lang);
				$(this).selectmenu("destroy").selectmenu({ style: "dropdown" });
			} catch(e){}
		});
		language.translate();
	},
	set: function(lang){
		if(language.debug>0) console.log('language.set('+lang+')');
		if(language.languages.indexOf(lang)>-1) {
			// Set Interface Language
			language.lang = lang;
			language.translate();
			// Store User Language
			var user = DB.getConfig('user');
			if(!user) user = {};
			user.lang = language.lang;
			DB.setConfig('user',user);
		}
	},
	translate: function(){
		if(language.debug) console.log('language.translate()');
		var els = $('*[data-translate]');
		var am = els.length;
		$.each(els,function(i){
			if($(this).attr('placeholder')!==undefined) $(this).attr('placeholder',language.t($(this).attr('data-translate'),$(this).attr('placeholder')));
			else $(this).html(language.t($(this).attr('data-translate'),$(this).html()));
		});
	},
	printUnfound: function(){
		var str = "";
		var keys = Object.keys(language.unfound);
		for(var z=0;z<keys.length;z++)
			str = str+", "+keys[z]+": '"+language.unfound[keys[z]]+"'";
		console.log("UNFOUND VOCABULARY FOR "+USERS.self.language);
		console.log(str);
	},
	t: function(id,html){
		if(language.langs[language.lang]===undefined || language.langs[language.lang][id]===undefined) {
			console.log('Did not find term '+id+' for language '+language.lang);
			language.unfound[id] = html;
			return id.replace("_", " ");
		} else return language.langs[language.lang][id];
	},
	unfound: {},
	langs: {},
}

language.langs.en = {
		_TITLE: 'English',
		abort: 'Abort',
		Abort: 'Abort',
		About: 'About',
		About_choose_to_start: 'Where do you wanna start?',
		About_chats: 'Watch the latest posts and messages',
		About_chats_long: 'Chats show all forums within your courses as well as private messages shared with others.<br /><br />This function summarizes the flow of information over all moodle instances you are connected with.',
		About_courses: 'Overview of all your courses',
		About_courses_long: 'The Courses-Section lists all your courses in all connected services and let you navigate through the course contents.<br /><br />With a short tap you can access all contents of those courses instantly.',
		About_contacts: 'Contact your classmates directly',
		About_contacts_long: 'Within the Contacts-Section you find a list of all peoply you are connected with - regardless in which of the services you are connected to.<br /><br />Instantly you can start sending private messages to all those people, or search within a specific service for further persons.<br /><br />Some of the services allow the founding of groups and joining them. This function is also provided in this section.',
		About_profile: 'Upload your foto and manage settings',
		About_profile_long: 'You can set a personal fotograph that is used as your avatar within eduMessenger. Furthermore you can change your personal data and password in this section.',
		About_instances: 'Connect to additional services',
		About_instances_long: 'MOODLE-Administrators can enrol their MOODLEs into eduMessenger. You can connect to many of them, as far as you have an account or are allowed to create one...',
		Accept_agreement: 'I read, understood and agree with the <a href="#terms_of_use" data-transition="flip">Terms of Use</a> and the <a href="#eula" data-transition="flip">End User Licence Agreement</a>',
		Accept_agreement_necessary: 'You need to read and agree with our Terms of Use and End User Licence Agreement',
		Accept_invitation: 'Join group',
        Accesscard: 'Accesscard',
        Accesscard_description: 'This accesscard is used to enrol you in various organizations. Using the "secret" (containing your userid, a hash-tag and a random phrase) a manager of an organization is able to make you a member of this particular organization.<br /><br />If your accesscard was issued to you by an authority and you were not given a separate password, then the red marked phrase is your initial password.<br /><br /><strong>In that case we strongly advise you to change your password immediately!</strong>.',
		Action_pending: 'Action pending',
		Actions: 'Actions',
		Activate: 'Activate',
		Activation: 'Activation',
        Add: 'Add',
        Add_content: 'Add content',
		Add_discussion: 'New topic',
		Add_group: 'Add group',
        Add_member: 'Add member',
        Add_member_by_code: 'Enter codes',
        Add_member_by_qr: 'Scan QR-Codes',
        Add_member_role: 'Select role',
		Add_message: 'Add message',
		Add_post: 'Add post',
        Add_section: 'Add section',
		Add_to_tasks: 'Add to list',
        ago_just_now: 'Just now',
        ago_days: '{days} days ago',
        ago_hours: '{hours} hours ago',
        ago_minutes: '{minutes} minutes ago',
        ago_months: '{months} months ago',
        ago_months_last: 'last month',
        ago_seconds: '{seconds} seconds ago',
        All_courses: 'All courses',
        All_groups: 'All groups',
		All_users: 'All Users',
		Allows_registration: 'Allows registration',
		Allows_groupcreation: 'Allows group creation',
		Already_registered: 'Already registered',
		Already_registered_with_another_instance: 'You already used <strong>{email}</strong> to register with instance {instancetitle}. Please register using this instance before connecting additional moodle instances!',
		Assessed_0: 'No Grades',
		Assessed_1: 'Average',
		Assessed_2: 'Amount',
		Assessed_3: 'Maximum',
		Assessed_4: 'Minimum',
		Assessed_5: 'Sum',
		Attach: 'Attach',
		Attach_appearin: 'Video-Chat',
		Attach_etherpad: 'Etherpad',
		Attach_file: 'Attach file',
		Attach_resource: 'Resource',
		Attachments: 'Attachments',
        Available_services: 'Available',
		Availability: 'Availability',
		Availability_infotext: 'Using Availability you can specify the times when you want to be notified by Push Notifications',
		Back: 'Back',
        Background: 'Background',
		Change_pwd: 'Change Password',
		Change_pwd_changed: 'Password was changed successfully',
		Change_pwd_current: 'Current Password',
		Change_pwd_new: 'New Password',
		Change_pwd_new_repeat: 'Repeat Password',
		Chats: 'Chats',
		Choose_a_foto: 'Choose foto',
		Choose_service_for_this_chat: 'Choose a service for this chat...',
		Clear_files: 'Clear files',
		Close: 'Close',
		Code: 'Activation code',
		Confirm: 'Confirm',
		Confirm_eMail: 'Confirm e-Mail',
		Connect: 'Connect',
        connect_site: 'Connect to Moodle-Site',
		Connect_service: 'Connect service',
		Connect_service_message: 'If you want to connect to a service you need to be already registered with this service. If this is not '+
				'the case please use the alternative option',
		Connect_to_lms: 'Connecting to LMS...',
		Connect_to_resource: 'Loading resource...',
		Connection_lost: '<p>It seems you have no connection to our servers. Please check the following:</p><ol><li>Your Device is connected to a network</li><li>Your Device can open Webpages (internet works)</li></ol><p>If you checked your device the connection error may be due to maintenance. Please be patient and try again in a few minutes!</p><a href="#" onclick="app.initialize();" data-role="button" data-icon="refresh">Retry</a><p>If the problem persists please contact our Helpdesk!</p>',
		Connected_services: 'Connected',
		Contact: 'Contact',
		Contact_not_found_q: 'Find person',
		Contact_support: 'Contact support',
		contact_to: 'Contact',
		Contacts: 'Contacts',
		Content: 'Content',
		Copied: 'Copied',
		Course: 'Course',
		Courses: 'Courses',
		current_pwd_wrong: 'Current password wrong',
		Create_group: 'Create group',
		Create_vault: 'Create vault',
        Data_cleared: 'Data cleared',
		Default: 'Default',
		Delete_all_attachments_q: 'Delete all attachments?',
		Disconnect: 'Disconnect',
		Disconnect_app: 'Disconnect',
        Disconnect_device_all: 'Disconnect all devices',
        Disconnect_device_this: 'Disconnect this device',
		Discussion: 'Topic',
		Discussions: 'Topics',
		Discussion_title_must_not_be_empty: 'Discussion-Title must not be empty',
		Discussion_title_must_contain_text: 'Discussion-Title must contain text',
        Down: 'Down',
		eMail: 'e-Mail',
		Email: 'e-Mail',
		Empty_message_not_allowed: 'Empty messages are not allowed',
		Enter_my_group_message: 'Hi! This is an invitation for you to join my group \'{coursename}\' on eduMessenger. Just enter the '+
				'invitation key {key} and join my group. Hint: This invitation expires on {expiry}',
		Enter_my_group_subject: 'eduMessenger Invitation',
		Etherpad: 'Etherpad',
        Expand: 'Expand',
        Experience_levels: 'Experience levels',
		Feature_not_yet_working: 'This feature is not yet available!',
		Fetch: 'Fetch',
		File_upload_failed: 'File-Upload failed!',
		File_maximum_exceeded: 'Maximum amount of attachments exceeded!',
		File_too_big: 'File too big!',
		Filter: 'Filter',
		Finish_registration: 'Enter',
		Firstname: 'Firstname',
		Forgot_password: 'Forgot your password',
		Forum: 'Forum',
        Forum_and_edumessenger: 'Forum and eduMessenger',
		Forward: 'Forward',
		Forward_invitation: 'Forward invitation',
		Founding_of_group_topic: 'Founding of Group',
		Founding_of_group_text: 'I founded the group {fullname}',
		from: 'from',
		Go_left: 'Go Left',
		Go_right: 'Go Right',
		Grade: 'Grade',
		Group: 'Group',
		Groups: 'Groups',
		Hello: 'Hello',
		Hello_message: 'Please enter your e-Mail address below and check if it is correct. You will receive an email '+
				'containing a \'One Time Token\' to prove you are the owner of the given address. Just enter that token on the next '+
				'page and you can start messaging in an instance!',
		Hide_this_group: 'Hide group',
		I_dont_have_moodle_yet: 'I don\'t use MOODLE yet',
		I_understood: 'I understood',
		If_you_have_moodle_start_with_service: 'Use one of the following services to start immediatley:',
		If_you_have_no_moodle_you_can_register: 'If you don\'t use MOODLE yet you can still register within a few steps.',
		Images_saved: 'Images saved!',
		Images_not_saved: 'Images could NOT be saved!',
		Import_failed: 'Import failed!',
		Import_successfull: 'Import successfull!',
		Import_stuff: 'Import Stuff',
		Instance_data_loading: 'Login successfull, your data is loading in the background. This may take some time... Please be patient.',
		Invalid_email: 'Invalid e-Mail Address',
		invalid_parameter_exception: 'Invalid Parameter given',
		Invitation: 'Invitation',
		Invitation_key: 'Invitation Key',
		Invitation_message_key: 'With this key other people can enter this group',
		Invitation_message_hint: 'Hint: this invitation key is valid until',
		Invite: 'Invite to this group',
		Language: 'Language',
		Lastname: 'Lastname',
		loading: '<center><img src="img/ajax-spinner.gif" alt="loading..." style="max-height: 1em; width: auto; height: auto;" /></center>',
		Loading_info: 'All data is being loaded. Interface may respond slowly while everything is set up. Please be patient!',
		loading_instances: 'Loading Services',
		Loading_data: 'Data needs to be loaded from Server',
        login: 'login',
		Login: 'Login',
        Login_failed: 'Login failed',
        Login_failed_on_site: 'Login failed on site {sitename}. Please login again!',
        Login_failed_unspecified: 'Login failed due to unspecified error',
		Login_not_successful: 'Login failed',
		Mail_empty: 'e-Mail Address must not be empty',
        Management: 'Management',
		Mark_all_as_read: 'Mark all as read',
		Markdown_bullets: 'Bullet points',
		Markdown_description: 'You can use the markdown format to enhance your texts. A complete description of all fatures is available on the',
		Markdown_emphasise: 'Emphasising Text',
		Markdown_format: 'Markdown format',
		Markdown_headings: 'Headings',
		Markdown_list_indented: 'Indented lists',
		Markdown_numbering: 'Numbered lists',
		Markdown_weblinks: 'Weblinks',
		Maximum_n_files_m_bytes: 'Maximum are {n} files with {m} per file',
		Me: 'Me',
		Members: 'Members',
		Message_must_not_be_empty: 'Message must not be empty',
		Message_was_not_saved: 'Message was not saved',
		Messages: 'Messages',
        moodle_but_no_messenger: 'This site seems to be a moodle-site, but unfortunately the <a href="https://moodle.org/plugins/local_edumessenger" target="_system">eduMessenger-Plugin</a> is not installed our outdated. Please tell your Moodle-Siteadministrator about this issue!',
        My_courses: 'My courses',
		My_data: 'My Data',
		My_data_text: 'On this page we show you everything that we stored in our database about you.',
		Name: 'Name',
		Name_of_group: 'Name of group',
		New_message: 'New Message',
		New_to_edumessenger: 'New to eduMessenger',
		New_topic: 'New Topic',
		No: 'No',
		Nobody_found: 'Sorry, nobody found',
        No_discussion_so_far: 'There is no discussion in this forum... be the first?',
		No_grade: 'No Grade',
		No_info: 'No Information',
		No_instance_allows_coursecreation: 'Sorry, you need to connect to a service that supports Creation of Courses',
        No_permission: 'No Permission',
		Not_supported_by_browser: 'Not supported by this browser!',
		Not_supported_by_instance: 'Not supported by this instance!',
        Notification_Forum_Mail: 'Receive Forum-Updates via e-Mail',
        Notification_Forum_Push: 'Receive Forum-Updates via Push-Notification',
        Notification_Message_Mail: 'Receive internal Messages via e-Mail',
        Notification_Message_Push: 'Receive internal Messages via Push-Notification',
        Notifications: 'Notifications',
		Nothing: 'Nothing',
		OK: 'OK',
		On_behalf: 'I don\'t have an E-Mail Address',
		On_behalf_text: 'It is possible to register using the Mail-Address of another person (e.g. friends, family. teachers). All communication concerning account activation, password reset etc. will be done using this E-Mail Address. To identify users they have to choose a username, which will be appended to the E-Mail Address. Registration will be done using the Address "<strong>FriendsMail+Username@Domain</strong>", e.g. susan@myschool.org becomes to susan+peter@myschool.org.',
		On_behalf_username: 'Username',
		On_behalf_email: 'Teachers E-Mail',
		Open: 'Open',
        Open_as_user: 'Open with the following account',
		Open_vault_automatically: 'Open automatically',
		Opened_services: 'Open Services',
		Other: 'Other',
		Password: 'Password',
		Password_manager: 'Password Manager',
		Password_must_not_be_empty: 'Password must not be empty',
		Password_wrong: 'Wrong password!',
		Passwords_dont_match: 'Passwords don\'t match',
		Permissions: 'Permissions',
		Pool: 'Tasks',
		Pool_empty: 'Double tip on posts to store them as task!',
		Pool_inbox: 'Inbox',
		Pool_inbox_sendto: 'Send this post to recipients task-inbox',
		Pool_hot: 'Hot',
		Pool_star: 'Star',
        Posts: 'Posts',
		Please_check_your_data_and_provide_your_password: 'Please check your data and provide a password',
		Please_enter_your_code: 'Please enter you activation code that we sent you by e-Mail',
        Please_restart_app: 'Please restart app to login again!',
        Please_try_again: 'Please try again in a few moments',
		Pro_features: 'Pro Features',
		Proceed: 'Proceed',
		Proceed_registration_message: 'If you already received an activation code you can proceed to the next step',
		Proceed_I_already_have_a_code: 'Step 2 - I already have an activation code',
		Profile: 'Profile',
		Purchases: 'Purchases',
		Purchase_edumessengerproabo: 'eduMessenger Pro Abo',
		Purchase_not_supported: 'Purchases not supported on this platform',
		Purchase_requires_proabo: 'This feature requires a Pro-Subscription!',
		Purchase_subscribe: 'subscribe',
		Purchase_validity: 'Validity',
        Question_subjects: 'Question subjects',
		Really_import: 'Really import?',
		Really_disconnect: 'Really disconnect from this service?',
        Really_disconnect_from_site: 'Really cut connection to {username} from site {sitename}?',
		Really_remove: 'Really remove?',
		Really_remove_group: 'Really delete group?',
		Refresh_data: 'Refresh all data',
		Register: 'Register',
		Register_moodle_in_edumessenger: 'Your MOODLE within eduMessenger?',
		Register_service: 'Register service',
		Register_service_message: 'If you register with a service your data has to be shared with this service. Services are'+
				'hosted by external parties. If you want to connect to a service you are already registered with please use '+
				'the alternative option',
		Register_service_password_message: 'If you register you <b>must</b> provide the password you used for eduMessenger! '+
				'This ensures that only you register with external services and agree to transfer your data!',
		Remove: 'Remove',
		Remove_group: 'Remove group',
		Remove_group_last_teacher: 'You are the last teacher in this group. If you resign the whole group will be <b>irrecoverably</b> removed!',
		Repeat_password: 'Password repeat',
		Request_new_password: 'Request new password',
		Request_new_password_check_mail: 'New Password was sent by e-Mail. Please also check your SPAM-Filter!',
		Reset: 'Reset',
		Restart_registration: 'Restart registration',
		Restricted_services: 'Private Services',
		Restricted_services_hint: 'Private Services only show up, if you know their name',
		Role_coursecreator: 'Course creator',
		Role_guest: 'Guest',
		Role_manager: 'Manager',
		Role_student: 'Student',
		Role_trainer: 'Trainer',
		Role_trainer_nonedit: 'Non-Editing Trainer',
		Save: 'Save',
		Scan_QR: 'Scan QR Code',
		Score: 'Score',
		Show_more: 'Show more',
		Search_contact: 'Search contact',
		Search_field: 'Search field',
		Search_now: 'Perform search',
		Search_value: 'Search value',
        Sent_using: 'This message was sent using ',
		Service: 'Service',
		Services: 'Services',
        Settings: 'Settings',
        Sites: 'Moodle-Sites',
		Skip: 'Skip',
        Stuck_here: 'Stuck here',
		Students: 'Students',
        Subject: 'Subject',
        Submenu: 'Submenu',
        Support: 'Support',
		Teachers: 'Teachers',
		This_contact_does_not_exist_on_the_selected_service: 'This contact does not exist on the selected service',
		This_person: 'this person',
		Timezone: 'Timezone',
		'timezone--12': 'UTC-12',
		'timezone--11': 'UTC-11',
		'timezone--10': 'UTC-10',
		'timezone--9': 'UTC-9',
		'timezone--8': 'UTC-8',
		'timezone--7': 'UTC-7',
		'timezone--6': 'UTC-6',
		'timezone--5': 'UTC-5',
		'timezone--4': 'UTC-4',
		'timezone--3': 'UTC-3',
		'timezone--2': 'UTC-2',
		'timezone--1': 'UTC-1',
		'timezone-0': 'UTC',
		'timezone-1': 'UTC+1',
		'timezone-2': 'UTC+2',
		'timezone-3': 'UTC+3',
		'timezone-4': 'UTC+4',
		'timezone-5': 'UTC+5',
		'timezone-6': 'UTC+6',
		'timezone-7': 'UTC+7',
		'timezone-8': 'UTC+8',
		'timezone-9': 'UTC+9',
		'timezone-10': 'UTC+10',
		'timezone-11': 'UTC+11',
		'timezone-12': 'UTC+12',
		Title: 'Title',
		to: 'to',
		Token_for__x__expired: 'Your Token for _x_ expired',
        Toolbox: 'Toolbox',
		Topic_title: 'Title',
		Topic_content: 'Content',
		Type: 'Type',
        Unknown: 'Unknown',
		Unkown_error_occurred: 'An unknown error occurred',
        Up: 'Up',
		Update: 'Update',
		Update_hide: 'Hide this information',
		Update_info: 'We improved eduMessenger and provided a smart-upgrade for this app. It is advised perform the update as soon as possible. If you are in the middle of writing something, you can finish your work before.<br /><br />To perform the update please press the following button or kill and restart the app.',
		Update_now: 'Update now',
		Upload: 'Upload',
		Upload_resource: 'Manage Contents',
        url_of_moodle_site: 'Url of Moodle-Site',
		user_does_not_exist: 'User does not exist',
		Username: 'Username',
		Username_or_eMail: 'Username', // e-Mail removed as this is used to login in moodle-instance.
		webservice_access_exception: 'Use of this function was not allowed by MOODLE-Administrator',
		Webview_missing: 'Error: Webview invalid',
		Welcome: 'Welcome',
		Welcome_guide: 'Guide',
		Welcome_text: 'Welcome to eduMessenger!',
		Which_language_do_you_speak: 'Which language do you speak',
		Vault_contains: 'Contains Password of',
		Vault_is_opened: 'Vault is opened!',
		Videochat: 'Videochat',
        View_hidden: 'Hidden courses',
		Yes: 'Yes',
		You_have_no_contacts_so_far: 'You have no contacts so far',
		You_have_no_conversations: 'You have no conversations',
	};

language.langs.de = {
		_TITLE: 'Deutsch',
		abort: 'Abbrechen',
		Abort: 'Abbrechen',
		About: 'Über',
		About_choose_to_start: 'Wo willst du starten?',
		About_chats: 'Deine neuesten Posts und Nachrichten',
		About_chats_long: '"Chats" zeigt alle Foren und Privatnachrichten aus allen Diensten / Kursen.<br /><br />Somit fasst diese Funktion den gesamten Informationsfluss aus allen Diensten zusammen, mit denen du verbunden bist.',
		About_courses: 'Übersicht über alle Kurse',
		About_courses_long: 'Die Kursliste zeigt alle Kurse an in denen du eingeschrieben bist. So kannst du einfach die Kursinhalte auflisten und diese mit einem Tap aufrufen!',
		About_contacts: 'Kontaktiere Freunde direkt',
		About_contacts_long: 'Die Kontakte-Seite zeigt dir eine Liste all jener Personen an, mit denen du in Verbindung stehst - egal über welchen Dienst.<br /><br />Natürlich kannst du die verbundenen Dienste nach zusätzlichen Personen durchsuchen und diese sofort kontaktieren.<br /><br />Einige Dienste erlauben die Erstellung eigener Lerngruppen. Diese Funktion findest du ebenfalls hier.',
		About_profile: 'Lade ein Foto hoch und verwalte deine Einstellungen',
		About_profile_long: 'Hier kannst du ein persönliches Foto hochladen, welches als Avatar im eduMessenger genutzt wird. Außerdem kannst du hier deine persönlichen Daten und dein Passwort ändern.',
		About_instances: 'Verbinde zu zusätzlichen Diensten',
		About_instances_long: 'Hier kannst du zusätzliche Dienste verbinden. Bei "privaten" Diensten muss du bereits einen Zugang haben, bei "offenen" Diensten kannst du dich selbst einschreiben. Einige davon ermöglichen die Erstellung von Lerngruppen.',
		Accept_agreement: 'Ich habe die <a href="#terms_of_use" data-transition="flip">Nutzungsbedingungen</a> und die <a href="#eula" data-transition="flip">Endbenutzervereinbarung</a> gelesen, verstanden, und akzeptiere sie.',
		Accept_agreement_necessary: 'Du musst mit unseren Nutzungsbedingungen und der Endbenutzer-Vereinbarung einverstanden sein!',
		Accept_invitation: 'Gruppe beitreten',
        Accesscard: 'Zugangskarte',
        Accesscard_description: 'Die Zugangskarte wird verwendet um Sie in zusätzlichen Schulen aufzunehmen. Mittels des "secret" (Kombination aus Benutzer-ID, # und einer zufälligen Buchstabenfolge) kann ein/e Manager/in einer Schule Sie zum Mitglied der Schule ernennen.<br /><br />Sofern Ihnen die Zugangskarte von einer dritten Person ausgehändigt wurde und Sie kein separates Passwort erhalten haben, ist die Buchstabenfolge zugleich Ihr Startpasswort. <strong>In diesem Fall sollten Sie dieses möglichst rasch ändern</strong>!',
		Action_pending: 'Aktion wird bereits durchgeführt!',
		Actions: 'Aktionen',
		Activate: 'Activate',
		Activation: 'Aktivierung',
        Add: 'Hinzufügen',
        Add_content: 'Inhalt hinzufügen',
		Add_discussion: 'Neues Thema',
        Add_member: 'Teilnehmer/in hinzufügen',
        Add_member_by_code: 'Codes eingeben',
        Add_member_by_qr: 'QR Codes scannen',
        Add_member_role: 'Rolle wählen',
		Add_message: 'Nachricht senden',
		Add_group: 'Gruppe hinzufügen',
		Add_post: 'Antworten',
        Add_section: 'Abschnitt hinzufügen',
		Add_to_tasks: 'Zur Aufgabenliste',
        ago_just_now: 'Gerade eben',
        ago_days: 'vor {days} Tagen',
        ago_hours: 'vor {hours} Stunden',
        ago_minutes: 'vor {minutes} Minuten',
        ago_months: 'vor {months} Monaten',
        ago_months_last: 'letztes Monat',
        ago_seconds: 'vor {seconds} Sekunden',
        All_courses: 'Alle Kurse',
        All_groups: 'Alle Gruppen',
		All_users: 'Alle Teilnehmer/innen',
		Allows_registration: 'Registrierung erlaubt',
		Allows_groupcreation: 'Gruppenerstellung erlaubt',
		Already_registered: 'Bereits registriert',
		Already_registered_with_another_instance: 'Du bist bereits als <strong>{email}</strong> via {instancetitle} registriert. Bitte melde dich mit diesem Dienst an, bevor du zusätzliche Dienste hinzufügst!',
		Assessed_0: 'Keine Bewertung',
		Assessed_1: 'Mittelwert',
		Assessed_2: 'Anzahl',
		Assessed_3: 'Maximalwert',
		Assessed_4: 'Minimalwert',
		Assessed_5: 'Summe',
		Attach: 'Anfügen',
		Attach_appearin: 'Video-Chat',
		Attach_etherpad: 'Etherpad',
		Attach_file: 'Datei',
		Attach_resource: 'Ressource',
		Attachments: 'Anhänge',
        Available_services: 'Verfügbar',
		Availability: 'Erreichbarkeit',
		Availability_infotext: 'Mittels der Erreichbarkeitseinstellungen kannst du dir aussuchen, wann du Push Benachrichtigungen erhalten willst.',
		Back: 'Back',
        Background: 'Hintergrund',
		Change_pwd: 'Passwort ändern',
		Change_pwd_changed: 'Passwort erfolgreich geändert!',
		Change_pwd_current: 'Aktuelles Passwort',
		Change_pwd_new: 'Neues Passwort',
		Change_pwd_new_repeat: 'Passwort Wiederholung',
		Chats: 'Chats',
		Choose_a_foto: 'Wähle ein Foto',
		Choose_service_for_this_chat: 'Wähle einen Dienst für diesen Chat...',
		Clear_files: 'Liste leeren',
		Close: 'Schließen',
		Code: 'Freischalt-Code',
		Confirm: 'Bestätigen',
		Confirm_eMail: 'e-Mail bestätigen',
		Connect: 'Verbinden',
        connect_site: 'Moodle verbinden',
		Connect_service: 'Dienst verbinden',
		Connect_service_message: 'Wenn du einen Dienst verbinden möchtest, musst du dort bereits registriert sein. Dies ist der Fall, wenn du '+
				'bspw. das MOODLE deiner Schule in dieser App verwenden willst. Sofern du dich bei einem Dienst erst '+
				'registrieren musst, nutze bitte die Option',
		Connect_to_lms: 'Verbinde mit LMS...',
		Connect_to_resource: 'Lade Ressource...',
		Connection_lost: '<p>Scheinbar besteht keine Verbindung zu unseren Servern. Bitte überprüfen Sie folgendes:</p><ol><li>Ihr Gerät ist mit einem Netzwerk verbunden</li><li>Ihr Gerät kann Webseiten öffnen (Internet funktioniert)</li></ol><p>Falls Ihr Gerät über eine Internetverbindung verfügt kann es sich um ein Wartungsfenster unserer Server handelt. Bitte versuchen Sie es in ein paar Minuten erneut!</p><a href="#" onclick="app.initialize();" data-role="button" data-icon="refresh">Retry</a><p>Falls das Problem weiter besteht kontaktieren Sie bitte unseren Helpdesk!</p>',
		Connected_services: 'Verbunden',
		Contact: 'Kontakt',
		Contact_not_found_q: 'Person suchen',
		Contact_support: 'Hilfe holen',
		contact_to: 'Kontaktieren',
		Contacts: 'Kontakte',
		Content: 'Inhalt',
		Copied: 'Kopiert',
		Course: 'Kurs',
		Courses: 'Kurse',
		Create_group: 'Gruppe anlegen',
		Create_vault: 'Tresor anlegen',
		current_pwd_wrong: 'Aktuelles Passwort falsch',
        Data_cleared: 'Daten entfernt',
		Default: 'Default',
		Delete_all_attachments_q: 'Alle Anhänge löschen?',
		Disconnect: 'Trennen',
		Disconnect_app: 'Abmelden',
        Disconnect_device_all: 'Von allen Geräten abmelden',
        Disconnect_device_this: 'Von diesem Gerät abmelden',
		Discussion: 'Thema',
		Discussions: 'Themen',
		Discussion_title_must_not_be_empty: 'Diskussionstitel darf nicht leer sein',
		Discussion_title_must_contain_text: 'Diskussionstitel muss Text enthalten',
        Down: 'Hinunter',
		eMail: 'e-Mail',
		Email: 'Email',
		Empty_message_not_allowed: 'Leere Nachrichten sind nicht erlaubt',
		Enter_my_group_message: 'Hallo! Tritt meiner eduMessenger-Gruppe {coursename} bei. '+
			'Der Schlüssel lautet {key}. Hinweis: Diese Einladung ist gültig bis {expiry}!',
		Enter_my_group_subject: 'eduMessenger Einladung',
		Etherpad: 'Etherpad',
        Expand: 'Ausklappen',
        Experience_levels: 'Erfahrungslevels',
		Feature_not_yet_working: 'Dieses Feature steht derzeit noch nicht zur Verfügung!',
		Fetch: 'Abrufen',
		File_upload_failed: 'Datei-Upload fehlgeschlagen!',
		File_maximum_exceeded: 'Maximale Anzahl an Dateien überschritten!',
		File_too_big: 'Die Datei ist zu groß!',
		Filter: 'Suche',
		Finish_registration: 'Anmelden',
		Firstname: 'Vorname',
		Forgot_password: 'Passwort vergessen',
		Forum: 'Forum',
        Forum_and_edumessenger: 'Forum und eduMessenger',
		Forward: 'Forward',
		Forward_invitation: 'Einladung weitergeben',
		Founding_of_group_topic: 'Gründung der Gruppe',
		Founding_of_group_text: 'Ich habe soeben die Gruppe {fullname} gegründet!',
		from: 'von',
		Go_left: 'Go Left',
		Go_right: 'Go Right',
		Grade: 'Bewertung',
		Group: 'Gruppe',
		Groups: 'Gruppen',
		Hello: 'Hallo',
		Hello_message: 'Bitte gib deine e-Mail Adresse bekannt und überprüfe, ob sie korrekt ist. Kurz darauf erhältst du eine e-Mail '+
				'mit einem \'One Time Token\' um zu prüfen, dass die Adresse tatsächlich dir gehört. Bitte gib diesen Token '+
				'auf der nächsten Seite ein und auch du kannst gleich starten Nachrichten auszutauschen!',
		Hide_this_group: 'Gruppe ignorieren',
		I_dont_have_moodle_yet: 'Ich habe noch keinen MOODLE-Zugang',
		I_understood: 'Ich habe verstanden',
		If_you_have_moodle_start_with_service: 'Mit einem Konto von folgenden Diensten kannst du sofort einsteigen:',
		If_you_have_no_moodle_you_can_register: 'Wenn du noch keinen MOODLE-Zugang hast, kannst du dich in wenigen Schritten registrieren.',
		Images_saved: 'Bilder gespeichert!',
		Images_not_saved: 'Bilder konnten NICHT gespeichert werden!',
		Import_failed: 'Import fehlgeschlagen!',
		Import_stuff: 'Importiere Material',
		Import_successfull: 'Import erfolgreich!',
		Instance_data_loading: 'Anmeldung erfolgreich, die Daten werden im Hintergrund geladen. Das kann ein wenig dauern - bitte um Geduld...',
		Invalid_email: 'Ungültige e-Mail-Adresse',
		invalid_parameter_exception: 'Ungültiger Parameter angegeben',
		Invitation: 'Einladung',
		Invitation_key: 'Schlüssel',
		Invitation_message_key: 'Mit dem folgenden Schlüssel können andere Personen dieser Gruppe beitreten',
		Invitation_message_hint: 'Hinweis: Der Schlüssel zur Gruppe ist gültig bis',
		Invite: 'Personen zur Gruppe einladen',
		Language: 'Sprache',
		Lastname: 'Nachname',
		loading: '<center><img src="img/ajax-spinner.gif" alt="loading..." style="max-height: 1em; width: auto; height: auto;" /></centere>',
		Loading_info: 'Alle Daten werden geladen. Bis alles eingerichtet ist, kann es zu Verzögerungen bei der Bedienung kommen!',
		loading_instances: 'Lade Services',
		Loading_data: 'Daten müssen noch vom Server geladen werden',
        login: 'anmelden',
		Login: 'Anmelden',
        Login_failed: 'Anmeldung fehlgeschlagen',
        Login_failed_on_site: 'Anmeldung auf Seite {sitename} fehlgeschlagen. Bitte melden Sie sich erneut an!',
        Login_failed_unspecified: 'Anmelgung wegen unbekanntem Fehler fehlgeschlagen',
		Login_not_successful: 'Anmeldung fehlgeschlagen',
		Mail_empty: 'e-Mail Adresse darf nicht leer sein',
        Management: 'Management',
		Mark_all_as_read: 'Alles gelesen',
		Markdown_bullets: 'Aufzählungen',
		Markdown_description: 'Mittels des Markdown Formats kann Text formatiert werden. Eine komplette Beschreibung der unterstützten Features ist verfügbar auf der',
		Markdown_emphasise: 'Text hervorheben',
		Markdown_format: 'Markdown Format',
		Markdown_headings: 'Überschriften',
		Markdown_list_indented: 'Eingerückte Listen',
		Markdown_numbering: 'Nummerierte Aufzählung',
		Markdown_weblinks: 'Weblinks',
		Maximum_n_files_m_bytes: 'Maximum sind {n} Dateien zu je {m}',
		Me: 'Ich',
		Members: 'Mitglieder',
		Message_must_not_be_empty: 'Nachricht darf nicht leer sein',
		Message_was_not_saved: 'Nachricht wurde nicht gespeichert',
		Messages: 'Nachrichten',
        moodle_but_no_messenger: 'Unter dieser Adresse ist eine Moodle-Plattform erreichbar, aber leider wurde das <a href="https://moodle.org/plugins/local_edumessenger" target="_system">eduMessenger-Plugin</a> nicht installiert oder ist veraltet. Bitte wenden Sie sich daher an Ihren Moodle-Siteadministrator oder Ihre Moodle-Siteadministratorin!',
        My_courses: 'Meine Kurse',
		My_data: 'Meine Daten',
		My_data_text: 'Auf dieser Seite kannst du nachsehen, was wir über dich gespeichert haben.',
		Name: 'Name',
		Name_of_group: 'Name der Gruppe:',
		New_message: 'Neue Nachricht',
		New_to_edumessenger: 'Neu beim eduMessenger',
		New_topic: 'Neues Thema',
		No: 'Nein',
		Nobody_found: 'Leider niemanden gefunden',
        No_discussion_so_far: 'Noch keine Diskussion hier. Sei der Erste!',
		No_grade: 'Keine Bewertung',
		No_info: 'Keine Information',
		No_instance_allows_coursecreation: 'Bitte verbinde zuerst mit einem Dienst, der die Erstellung von Gruppen erlaubt!',
        No_permission: 'Fehlende Berechtigung!',
		Not_supported_by_browser: 'In diesem Browser nicht verfügbar!',
		Not_supported_by_instance: 'Von dieser Instanz nicht unterstützt!',
		Nothing: 'Nichts',
        Notification_Forum_Mail: 'Erhalte Forum-Einträge via e-Mail',
        Notification_Forum_Push: 'Erhalte Forum-Einträge via Push-Benachrichtigung',
        Notification_Message_Mail: 'Erhalte interne Nachrichten via e-Mail',
        Notification_Message_Push: 'Erhalte interne Nachrichten via Push-Benachrichtigung',
        Notifications: 'Benachrichtigungen',
		OK: 'OK',
		On_behalf: 'Ich habe keine E-Mail Adresse',
		On_behalf_text: 'Es ist möglich sich mit der E-Mail Adresse einer anderen Person zu registrieren (bspw. Freunde, Familie, Lehrer/innen). Jegliche Kommunikation bezüglich Registrierung, Passwort-Rücksetzung etc. wird über die Adresse dieser Person durchgeführt. Um Nutzer/innen dennoch zu identifizieren muss ein eindeutiger Benutzername gewählt werden. Die Registrierung erfolgt über die E-Mail-Adresse "<strong>FremdeMail+Benutzername@Domain</strong>", also wird bspw. susanne@meineschule.at zu susanne+hansmaier@meineschule.at!',
		On_behalf_username: 'Benutzername',
		On_behalf_email: 'Lehrer/innen-E-Mail',
		Open: 'Öffnen',
        Open_as_user: 'Mit folgendem Konto öffnen',
		Open_vault_automatically: 'Öffne automatisch',
		Opened_services: 'Offene Dienste',
		Other: 'Sonstiges',
		Password: 'Passwort',
		Password_manager: 'Passwort Manager',
		Password_must_not_be_empty: 'Passwort darf nicht leer sein',
		Password_wrong: 'Falsches Passwort!',
		Passwords_dont_match: 'Passwörter stimmen nicht überein',
		Permissions: 'Rechte',
		Please_check_your_data_and_provide_your_password: 'Bitte überprüfe die Vollständigkeit deiner Daten und gib uns dein Passwort!',
		Please_enter_your_code: 'Bitte gib hier den Code aus der e-Mail ein',
        Please_restart_app: 'Bitte starten Sie die App neu um sich wieder anzumelden!',
        Please_try_again: 'Bitte versuchen Sie es in ein paar Sekunden noch einmal.',
		Pool: 'Aufgaben',
		Pool_empty: 'Tippe doppelt auf Nachrichten, um sie als Aufgabe zu hinterlegen!',
		Pool_inbox: 'Eingang',
		Pool_inbox_sendto: 'Dem Aufgabeneingang der Empfänger anfügen!',
		Pool_hot: 'Eilt',
		Pool_star: 'Später',
        Posts: 'Beiträge',
		Pro_features: 'Pro Features',
		Proceed: 'Weiter',
		Proceed_registration_message: 'Wenn du bereits einen Code erhalten hast, und deine Registrierung fortsetzen willst, klicke bitte hier:',
		Proceed_I_already_have_a_code: 'Schritt 2 - Ich habe schon einen Code',
		Profile: 'Profil',
		Purchases: 'Abonnements',
		Purchase_edumessengerproabo: 'eduMessenger Pro Abo',
		Purchase_not_supported: 'Abonnements werden auf dieser Plattform nicht unterstützt!',
		Purchase_requires_proabo: 'Dieses Feature benötigt ein Pro-Abonnement!',
		Purchase_subscribe: 'abonnieren',
		Purchase_validity: 'Gültigkeit',
        Question_subjects: 'Fragenkategorien',
		Really_import: 'Wirklich importieren?',
		Really_disconnect: 'Diesen Dienst wirklich trennen?',
        Really_disconnect_from_site: 'Wirklich Verbindung von {username} der Moodle-Site {sitename} trennen?',
		Really_remove: 'Wirklich entfernen?',
		Really_remove_group: 'Gruppe wirklich löschen',
		Refresh_data: 'Alle Daten neu laden',
		Register: 'Registrieren',
		Register_moodle_in_edumessenger: 'Dein MOODLE im eduMessenger?',
		Register_service: 'Dienst registrieren',
		Register_service_message: 'Wenn du einen Dienst registrieren möchtest werden deine Daten bei diesem Dienst hinterlegt und ein Zugangskonto erstellt. '+
				'Sofern du einen Dienst verbinden möchtest, bei dem du bereits ein Zugangskonto hast, nutze bitte die Option',
		Register_service_password_message: 'Bei der Registrierung <u>musst</u> du das Passwort benutzen, welches du bei der Einrichtung des eduMessengers '+
				'gewählt hast! So stellen wir sicher, dass auch wirklich nur du selbst deine Daten an zusätzliche Diensten weitergibst.',
		Remove: 'Entfernen',
		Remove_group: 'Gruppe löschen',
		Remove_group_last_teacher: 'Sie sind die letzte Lehrkraft in der Gruppe. Wenn Sie austreten, wird die ganze Gruppe <strong>unwiederbringlich</strong> gelöscht!',
		Repeat_password: 'Passwort Wiederholung',
		Request_new_password: 'Neues Passwort anfordern',
		Request_new_password_check_mail: 'Neues Passwort wurde per e-Mail versendet! Bitte auch im SPAM-Ordner nachsehen!',
		Reset: 'Zurücksetzen',
		Restart_registration: 'Restart Registration',
		Restricted_services: 'Private Dienste',
		Restricted_services_hint: 'Private Dienste werden nur aufgelistet, wenn du ihren Namen kennst!',
		Role_coursecreator: 'Kursersteller/in',
		Role_guest: 'Gast',
		Role_manager: 'Manager/in',
		Role_student: 'Schüler/in',
		Role_trainer: 'Lehrer/in',
		Role_trainer_nonedit: 'Lehrer/in ohne Schreibrecht',
		Save: 'Speichern',
		Scan_QR: 'QR Code einlesen',
		Score: 'Punkte',
		Show_more: 'Mehr anzeigen',
		Search_contact: 'Suche Kontakt',
		Search_field: 'Suchfeld',
		Search_now: 'Suche durchführen',
		Search_value: 'Suchwert',
        Sent_using: 'Diese Nachricht wurde gesendet mit ',
		Service: 'Dienst',
		Services: 'Dienste',
        Settings: 'Einstellungen',
        Sites: 'Moodle-Seiten',
		Skip: 'Überspringen',
        Stuck_here: 'Festgefahren',
		Students: 'Schüler/innen',
        Subject: 'Betreff',
        Submenu: 'Untermenü',
        Support: 'Hilfe',
		Teachers: 'Lehrer/innen',
		This_contact_does_not_exist_on_the_selected_service: 'Sorry, dieser Kontakt scheint auf dem gewählten Dienst nicht zu existieren!',
		This_person: 'diese Person',
		Timezone: 'Zeitzone',
		'timezone--12': 'UTC-12',
		'timezone--11': 'UTC-11',
		'timezone--10': 'UTC-10',
		'timezone--9': 'UTC-9',
		'timezone--8': 'UTC-8',
		'timezone--7': 'UTC-7',
		'timezone--6': 'UTC-6',
		'timezone--5': 'UTC-5',
		'timezone--4': 'UTC-4',
		'timezone--3': 'UTC-3',
		'timezone--2': 'UTC-2',
		'timezone--1': 'UTC-1',
		'timezone-0': 'UTC',
		'timezone-1': 'UTC+1',
		'timezone-2': 'UTC+2',
		'timezone-3': 'UTC+3',
		'timezone-4': 'UTC+4',
		'timezone-5': 'UTC+5',
		'timezone-6': 'UTC+6',
		'timezone-7': 'UTC+7',
		'timezone-8': 'UTC+8',
		'timezone-9': 'UTC+9',
		'timezone-10': 'UTC+10',
		'timezone-11': 'UTC+11',
		'timezone-12': 'UTC+12',
		Title: 'Titel',
		to: 'an',
		Token_for__x__expired: 'Das Token für _x_ ist abgelaufen',
        Toolbox: 'Toolbox',
		Topic_title: 'Titel',
		Topic_content: 'Inhalt',
		Type: 'Typ',
        Unknown: 'Unbekannt',
		Unkown_error_occurred: 'Unbekannter Fehler aufgetreten',
        Up: 'Hinauf',
		Update: 'Aktualisierung',
		Update_hide: 'Information ausblenden',
		Update_info: 'Wir haben eduMessenger verbessert und ein Smart-Update bereitgestellt. Es wird empfohlen möglichst bald das Update einzuspielen. Falls Sie gerade eine Nachricht verfassen, können Sie diese gerne noch fertigstellen. Um das Update einzuspielen drücken Sie bitte die folgende Schaltfläche, oder starten Sie diese App neu.',
		Update_now: 'Jetzt aktualisieren',
		Upload: 'Upload',
		Upload_resource: 'Inhalte verwalten',
        url_of_moodle_site: 'URL der Moodle-Seite',
		user_does_not_exist: 'Dieser Benutzer existiert nicht',
		Username: 'Benutzername',
		Username_or_eMail: 'Benutzername', // e-Mail removed as this is used to login in moodle-instance.
		webservice_access_exception: 'Der MOODLE-Admin hat die Nutzung dieser Funktion nicht erlaubt!',
		Webview_missing: 'Error: Webview ungültig',
		Welcome: 'Welcome',
		Welcome_guide: 'Einführung',
		Welcome_text: 'Willkommen beim eduMessenger!',
		Which_language_do_you_speak: 'Welche Sprache sprichst du',
		Vault_contains: 'Enthält Passwort von',
		Vault_is_opened: 'Passwort-Tresor ist offen!',
		Videochat: 'Videochat',
        View_hidden: 'Ausgeblendete Kurse',
		Yes: 'Ja',
		You_have_no_contacts_so_far: 'Du stehst noch mit niemandem in Kontakt',
		You_have_no_conversations: 'Du hast noch keine Konversationen.',
	};
